# pull official base image
FROM python:latest

# install python3 and pip
RUN apt-get update && apt-get install -y ncat python3-dev build-essential apt-utils

# set work directory
WORKDIR /app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY . .
RUN pip install -r requirements.txt
RUN groupadd -r user && useradd -r -g user user
RUN chown -R user:user /app
USER user